selab-hs/auction_project

- src/main/java/com/selab/auction/error/dto/ErrorMessage.java
- src/main/java/com/selab/auction/error/dto/ErrorResponse.java
- src/main/java/com/selab/auction/error/exception/BusinessException.java
- src/main/java/com/selab/auction/error/exception/GlobalExceptionHandler.java
- src/main/java/com/selab/auction/error/exception/item/NotExistItemException.java
- resolved #7 
- GlobalExcptionHandler 추가
- 도메인 별로 작업을 진행하다가 생성되는 Exception이 있으면 /error/exception/ 폴더 아래에 해당 도메인 패키지 만들고, 그 안에 exception class 추가하시면 될 것 같슴둥!
- 모든 error는 Dto인  `ErrorResponse` 를 통해 던져주세요!
-
> 🎨 [style/error-7] GlobalExceptionHandler 추가

- src/main/java/com/selab/auction/common/dto/ResponseDto.java
- resolved #0
- 공통 ResponseDto 추가
> :art: [style/responseDto] ResponseDto 추가

- src/main/java/com/selab/auction/error/dto/ErrorMessage.java
- src/main/java/com/selab/auction/error/exception/item/NotExistCategoryException.java
- src/main/java/com/selab/auction/item/controller/ItemController.java
- src/main/java/com/selab/auction/item/model/dto/ItemCreateRequest.java
- src/main/java/com/selab/auction/item/model/dto/ItemResponse.java
- src/main/java/com/selab/auction/item/model/dto/ItemsResponse.java
- src/main/java/com/selab/auction/item/model/entity/Item.java
- src/main/java/com/selab/auction/item/model/vo/Category.java
- src/main/java/com/selab/auction/item/repository/ItemRepository.java
- src/main/java/com/selab/auction/item/service/ItemService.java
- resolved #4 
- 상품 단건 및 전체 조회 API
- 상품 추가 API
- (수정 API 추가 및 조회 API 수정 예정!)
> ✨ [feature/items-4] 상품 조회 및 생성 구현

- src/main/java/com/selab/auction/common/controller/SwaggerController.java
- resolved #11 
- swagger url redirection 설정 완료
> :sparkles: [improve/swagger] Swagger API redirection 추가

- src/main/java/com/selab/auction/error/dto/ErrorMessage.java
- src/main/java/com/selab/auction/error/exception/auction/WrongRequestPrice.java
- src/main/java/com/selab/auction/item/model/entity/Auction.java
- src/main/java/com/selab/auction/participation/controller/AuctionController.java
- src/main/java/com/selab/auction/participation/model/dto/AuctionResponseDto.java
- src/main/java/com/selab/auction/participation/model/dto/CreateAuctionDto.java
- src/main/java/com/selab/auction/participation/model/entity/AuctionProgress.java
- src/main/java/com/selab/auction/participation/repository/AuctionRepository.java
- src/main/java/com/selab/auction/participation/service/AuctionService.java
- src/main/java/com/selab/auction/participation/service/AuctionServiceImpl.java
- 경매 참여 기능 추가
- 경매 참여 기능 추가
- Auction Entity 수정 및 CreateAuctionDto, AuctionResponseDto 추가
- WrongRequestPrice 를 통한 잘못된 경매가격 Exception 클래스 추가
- ErrorMessage Enum WRONG_REQUEST_PRICE 에러 메시지 추가
- 해당 Item의 기록이 없다면 기존 가격 이상, 있다면 해당 기록 + 기존 가격의 1% 이상 추가한 금액이어야 함. 아닐경우 WrongRequestPrice Exception 발생
> ✨[auction/participation-3] 경매 참여 기능 추가

- build.gradle
- src/main/java/com/selab/auction/config/redis/RedisConfig.java
- src/main/java/com/selab/auction/error/exception/GlobalExceptionHandler.java
- src/main/java/com/selab/auction/participation/controller/AuctionController.java
- src/main/java/com/selab/auction/participation/model/dto/CreateAuctionDto.java
- src/main/java/com/selab/auction/participation/repository/AuctionRepository.java
- src/main/java/com/selab/auction/participation/service/AuctionServiceImpl.java
- MethodArgumentNotValidException Exception 전역 처리 내용 추가
- Redis 의존성 추가 및 RedisConfig 작성
- Valid 의존성 추가
- 다른 도메인에서의 MethodArgumentNotValidException Exception 적용 여부
> ✨[Feature/valid-exception-14]Valid Exception 전역처리

- src/main/java/com/selab/auction/common/State.java
- src/main/java/com/selab/auction/common/dto/SwaggerNote.java
- src/main/java/com/selab/auction/error/dto/ErrorMessage.java
- src/main/java/com/selab/auction/error/exception/item/DeleteItemException.java
- src/main/java/com/selab/auction/item/controller/ItemController.java
- src/main/java/com/selab/auction/item/model/dto/ItemResponse.java
- src/main/java/com/selab/auction/item/model/dto/ItemUpdateRequest.java
- src/main/java/com/selab/auction/item/model/entity/Item.java
- src/main/java/com/selab/auction/item/model/vo/ItemState.java
- src/main/java/com/selab/auction/item/repository/ItemRepository.java
- src/main/java/com/selab/auction/item/service/ItemService.java
- resolved #4 
- 상품 수정 및 삭제 API 구현
- @Transactional 적용
- 추가 예외 처리 구현
> ✨[feature/items 4] 상품 수정 및 삭제 API 구현

- src/main/java/com/selab/auction/error/dto/ErrorMessage.java
- src/main/java/com/selab/auction/error/exception/auction/CompletedAuctionException.java
- src/main/java/com/selab/auction/error/exception/auction/WrongRequestPriceException.java
- src/main/java/com/selab/auction/error/exception/item/WrongItemStateException.java
- src/main/java/com/selab/auction/participation/service/AuctionServiceImpl.java
resolved #23 
- ItemState에 따른 경매 진행 수정
- 처음 경매 진행 시 ItemState 경매 진행 상태 Progress로 변경
- 현재 충돌로 인해 merge 불가능, 충돌 해결 필요
> 🎨[Style/auction-23] 경매 진행 상태에 따른 경매 내용 보완

- src/main/java/com/selab/auction/member/model/entity/BuyHistory.java
- src/main/java/com/selab/auction/member/model/entity/Member.java
- src/main/java/com/selab/auction/member/model/entity/SaleHistory.java
조회 성능을 높이기 위해 엔티티에 인덱싱을 적용하였다.
- resolved #16
Member Entity, BuyHistory Entity, SaleHistory Entity에 인덱스를 적용하였다. (설정 컬럼: 각 엔티티별 id)
컬럼을 적절히 설정했는지 확인 부탁드립니다.
> ✨ [feature/memberindex-16] Member 인덱싱 구현

- src/main/java/com/selab/auction/participation/model/entity/AuctionProgress.java
- resolved #16 
- index 추가
- index에 추가할 속성이 있는지
> ✨[Feature/auction-index-1]AuctionProgress Index 추가

- src/main/resources/application.yml
- resolved #33 
- yml 파일 있는 브런치를 이용하여 재 커밋 후 push
- 이전 yml과 동일한지
> - yml 파일 복구

- build.gradle
- src/main/java/com/selab/auction/error/exception/member/find/NotExistMemberException.java
- src/main/java/com/selab/auction/member/service/MemberSignUpService.java
- src/main/resources/logback-slack.xml
- 프로젝트 개발, 유지 보수 편의를 위해 공통 모듈을 개발한다.
- resolved #18
1. Jacoco 도입 (테스트 진행 시 코드 커버리지 확인 가능)
#
2. Error 발생 시 Slack 알림 기능 구현
혹시 깃에 올라가면 안 되는 내용들이 있는지 확인 부탁드립니다. (스크린샷 포함)
yml 파일 새로 적용 부탁드립니다.
> ✨ [feature/commonmodule-18] Jacoco 도입, Error 발생 시 Slack 알림 기능 구현

- src/main/java/com/selab/auction/item/controller/ItemController.java
- src/main/java/com/selab/auction/participation/controller/AuctionController.java
- resolved #36
CORS Config 이미 설정되어 있음
따라서 각 Controller에 CORS 어노테이션 적용
> ✨ [feature/cors-36] CORS 설정

- src/main/java/com/selab/auction/item/controller/ItemController.java
- src/main/java/com/selab/auction/member/controller/MemberController.java
- src/main/java/com/selab/auction/participation/controller/AuctionController.java
CORS Config가 등록되어 있으므로 따로 Annotation을 적용할 필요가 없다.
- resolved #39
각 Controller에 있는 @CrossOrigin Annotation을 제거하였다.
> 🔥 [feature/remove-cors-39] CORS Annotation 제거

- src/main/java/com/selab/auction/member/model/entity/Member.java
- src/main/java/com/selab/auction/participation/model/dto/AuctionBuyCommentResponseDto.java
- src/main/java/com/selab/auction/participation/model/dto/AuctionSaleCommentResponseDto.java
- src/main/java/com/selab/auction/participation/model/dto/CreateBuyCommentDto.java
- src/main/java/com/selab/auction/participation/model/dto/CreateSaleCommentDto.java
- src/main/java/com/selab/auction/participation/model/entity/AuctionBuyComment.java
- src/main/java/com/selab/auction/participation/model/entity/AuctionSaleComment.java
- src/main/java/com/selab/auction/participation/repository/AuctionBuyCommentRepository.java
- src/main/java/com/selab/auction/participation/repository/AuctionSaleCommentRepository.java
- src/main/java/com/selab/auction/participation/service/AuctionCommentService.java
- Comment 등록 시 별점 조회 및 멤버 별점 업데이트 진행
- resolved #43 
- Comment 등록 시 별점 조회 및 멤버 별점 업데이트 진행
- Member Entity에 dirty checking을 위한 grade update 메소드 추가
- 이후 경매 진행 이후 코멘트 등록이 가능하도록 유효성 검사 추가 예정
- 현재 AuctionCommentService Class에 있는 updateMemberGrade MemberService 클래스로 옮겨야 함
> ✨ [Feature/auction-43] Comment 별점 조회/변경

- src/main/java/com/selab/auction/member/service/MemberGradeUpdateService.java
- src/main/java/com/selab/auction/member/service/MemberUpdateGradeService.java
- src/main/java/com/selab/auction/participation/service/AuctionCommentService.java
AuctionCommentService 클래스의 updateMemberGrade Method를 member service package로 옮긴다.
- resolved #48
MemberUpdateGradeService Class를 추가하여 해당 메서드 이동
오류 안 나는지 확인해 주세요~
> 🚚 [move/updateMemberGrade-48] updateMemberGrade 이동

- scripts/DDL.sql
- src/main/java/com/selab/auction/AuctionApplication.java
- src/main/java/com/selab/auction/common/dto/PageDto.java
- src/main/java/com/selab/auction/config/redis/RedisConfig.java
- src/main/java/com/selab/auction/error/dto/ErrorMessage.java
- src/main/java/com/selab/auction/error/dto/ErrorResponse.java
- src/main/java/com/selab/auction/error/exception/GlobalExceptionHandler.java
- src/main/java/com/selab/auction/error/exception/member/DuplicateEmailException.java
- src/main/java/com/selab/auction/error/exception/member/DuplicateNicknameException.java
- src/main/java/com/selab/auction/error/exception/member/NotExistMemberException.java
- src/main/java/com/selab/auction/error/exception/member/PasswordCheckFailedException.java
- src/main/java/com/selab/auction/item/controller/ItemController.java
- src/main/java/com/selab/auction/item/repository/ItemRepository.java
- src/main/java/com/selab/auction/item/service/ItemService.java
- src/main/java/com/selab/auction/member/controller/MemberController.java
- src/main/java/com/selab/auction/member/service/MemberFindService.java
- src/main/java/com/selab/auction/member/service/MemberGradeUpdateService.java
- src/main/java/com/selab/auction/member/service/MemberSignUpService.java
- src/main/java/com/selab/auction/participation/controller/AuctionController.java
- src/main/java/com/selab/auction/participation/service/AuctionCommentService.java
- src/main/java/com/selab/auction/participation/service/AuctionServiceImpl.java
- resolved #50 
- 전체 프로젝트에 대한 코드 리펙토링
- 잘못된 로직에 대한 수정
- 변경이 필요한 부분에 대한 TODO 추가
- 변경 지점에 대해 내용 확인하시고, TODO도 확인 부탁드릴게요
> ⚡️ [Improve/all-50] 전반적인 코드 리펙토링 및 수정

- build.gradle
- src/main/java/com/selab/auction/config/security/SecurityConfig.java
- src/main/java/com/selab/auction/error/dto/ErrorMessage.java
- src/main/java/com/selab/auction/error/exception/member/signin/InacitveMemberException.java
- src/main/java/com/selab/auction/error/exception/member/signup/DuplicateEmailException.java
- src/main/java/com/selab/auction/error/exception/member/signup/DuplicateNicknameException.java
- src/main/java/com/selab/auction/error/exception/member/signup/PasswordCheckFailedException.java
- src/main/java/com/selab/auction/member/controller/MemberController.java
- src/main/java/com/selab/auction/member/model/dto/MemberSignInRequestDto.java
- src/main/java/com/selab/auction/member/model/dto/MemberSignInResponseDto.java
- src/main/java/com/selab/auction/member/repository/MemberRepository.java
- src/main/java/com/selab/auction/member/service/MemberSignUpService.java
- src/main/java/com/selab/auction/member/signin/security/AuthEntryPoint.java
- src/main/java/com/selab/auction/member/signin/security/MemberPrincipal.java
- src/main/java/com/selab/auction/member/signin/security/TokenAuthenticationFilter.java
- src/main/java/com/selab/auction/member/signin/security/TokenProvider.java
- src/main/java/com/selab/auction/member/signin/service/CustomMemberDetailService.java
- src/main/java/com/selab/auction/member/signin/service/MemberSignInService.java
회원 로그인 기능을 구현한다.
- resolved #41
1. 로그인 시 이메일, 비밀번호는 필수 입력 값입니다.
2. 휴면 회원일 경우 InactiveMemberException 발생
3. 추후 USER Role만 접근할 수 있는 URI 생성 시 Security Config 수정 필요
패키지 위치가 적절한지 확인 부탁드립니다.
또 적용해야 할 Valid가 있는지 피드백 부탁드립니다.
> ✨ [Feature/login-41] 로그인 기능 구현

- src/main/java/com/selab/auction/AuctionApplication.java
- src/main/java/com/selab/auction/item/repository/ItemRepository.java
- src/main/java/com/selab/auction/item/service/ItemService.java
- src/main/java/com/selab/auction/scheduler/service/SchedulerService.java
- 스케줄링 기간 처리
- resolved #47 
- ItemService 경매 상태 완료 변경, 경매 진행 중 조회 메소드 추가
- schedulerService 추가. 경매 기간 만료시 스케줄링 처리로 만료. 10분마다 실행
- 특이사항 혹은 더 나은 코드 유무
> ✨[Feature/auction-47] 경매 기간 만료시 스케줄링 처리

- src/main/java/com/selab/auction/item/service/ItemService.java
- src/main/java/com/selab/auction/scheduler/service/SchedulerService.java
- 스케줄링 서비스에서 해당 로직을 SchedulerService에서 처리하는 문제 수정 필요
- resolved #56 
- 해당 처리 로직 ItemService에서 처리하도록 변경
- 필요 변경 사항이 해당 사항이 맞는지 혹은 더 좋은 방법이 있는지
> ✨[Feature/auction-scheduler-56] 스케줄링 비즈니스로직 분할

- src/main/java/com/selab/auction/participation/controller/AuctionController.java
- src/main/java/com/selab/auction/participation/model/dto/CreateImmediatePurchaseDto.java
- src/main/java/com/selab/auction/participation/service/AuctionService.java
- src/main/java/com/selab/auction/participation/service/AuctionServiceImpl.java
- auction.participation url 수정
- 즉시 구매 기능 추가
- resolved #58 
- url 수정. 패키지명과 동일하도록 url에 /participation 추가
- 즉시 구매 기능 추가
- 유효성 검사 진행 코드에 변경사항 존재 유무
> ✨[Feature/auction - 58] 즉시 구매 기능 구현

- build.gradle
- src/main/java/com/selab/auction/item/service/ItemLockService.java
- src/main/java/com/selab/auction/item/service/ItemService.java
- src/test/java/com/selab/auction/item/ItemSaveTest.java
- 아이템 동시성 문제 해결
- resolved #68 
- JDK17버전 호환을 위한 Jacoco 버전 변경 ( 0.8.5 -> 0.8.8 )- Item 동시성 문제 해결을 위해 ItemLockService 생성
- ItemService save와 update를 ItemLockService를 거쳐서 적용
- 코드 개선 방안
- 테스트 코드 개선 방안
> [✨Feature/item-redisson] 아이템 동시성 문제 해결
